### PR TITLE
fix #23 issue with paths for pypdf2

### LINKED ISSUE #23: BUG: combine PDFs failing
**Describe the bug**
The `combine_pdfs` function is crashing a rstudio IDE on our singularity image, and, failing and producing an error when submitted as a job.

**To Reproduce**
```
library(demUtils)

test <- plot(x = 1:10, y = 1:10)
test2 <- plot(x = 1:100, y = 1:100)

pdf("~/test.pdf")
print(test)
dev.off()

pdf("~/test2.pdf")
print(test2)
dev.off()

input_paths <- c("~/test.pdf", "~/test2.pdf")
output_path <- "~/test_combined.pdf"

demUtils::combine_pdfs(input_paths, output_path)
```

**Expected behavior**
Function writes combined PDF to output path without error.

**Screenshots**
From error log:
```
Traceback (most recent call last):
  File "/{redacted path for IHME Rstudio singularity images}/container_cache.py", line 164, in <module>
    filepath = sys.argv[1]
IndexError: list index out of range
FATAL:   image format not recognized
```

**Desktop (please complete the following information):**
 - Singularity version `v2020.0.8`

**Additional context**
To qsub, I put this at the top of my script with the test code above:
```
if(interactive()) {
  demInternal::qsub(
    jobname = "test",
    code = "~/testing_combine_pdfs.R",
    shell = "/{path to demographics team shells}/exec.sh",
    fthread = 5,
    fmem = 20,
    h_rt = "01:00:00",
    archive = T,
    pass_argparse = list(),
    submit = T
  )
}
```

I haven't tested this, but I'd be curious to know if the python code is working and it's just the R wrapper that is failing.

### PR DESCRIPTION
**Pull request by chacalle**
## Describe changes

Fixes issue with paths for pypdf2. Documented more in the issue https://github.com/ihmeuw-demographics/demUtils/issues/23

## What issues are related

Fixes #23 

### Packages Repositories

* [X] Have you read the [contributing guidelines](https://github.com/ihmeuw-demographics/packageTemplate/wiki#guide-to-r-package-development) for `ihmeuw-demographics` R packages?
* [X] Have you successfully run `devtools::check()` locally?
* [x] Have you updated or added function (and vignette if applicable) documentation? Did you update the 'man' and 'NAMESPACE' files with `devtools::document()`?
* [ ] Have you added in tests for the changes included in the PR?
* [X] Do the changes follow the `ihmeuw-demographics` [code style](https://github.com/ihmeuw-demographics/packageTemplate/wiki/Code-style-guide)?
* [ ] Do the changes need to be immediately included in a new build of [`docker-base`](https://github.com/ihmeuw-demographics/docker-base) or [`docker-internal`](https://github.com/ihmeuw-demographics/docker-internal)? If so follow directions in those repositories to rebuild and redeploy the images.
* [ ] Do the changes require updates to other repositories which use this package? If yes, make the necessary updates in those repos, and consider integration tests for those repositories.

## Details of PR

The current test for this function uses the temp directory, I'm not sure we want a test writing in the home directory?

### CODE REVIEW

**Comment by krpaulson** [comment]
Looks like this is failing the package check on that function. Also, I identified that this function wasn't working while using a file path that didn't have a `~` included.

**Comment by chacalle** [comment]
Yeah there is a separate issue for fixing the installation of PyPDF2 on the github action workflows https://github.com/ihmeuw-demographics/demUtils/issues/17.

Can you try this in your use case again on the `v2020.0.9` image or provide another example that is breaking? Because the test in the package and the test documented in the issue are working now.

**Comment by krpaulson** [comment]
Ok so it wasn't `~` but I think we need to add instructions to not use any aliases (I was using a different IHME alias). Now I'm getting a different error.

```

*** caught illegal operation ***
address 0x2af0938a054c, cause 'illegal operand'

Traceback:
1: py_run_string_impl(paste0("import sys; sys.path.append('", system.file("python",     package = "reticulate"), "')"))
2: initialize_python(required_module, use_environment)
3: ensure_python_initialized()
4: py_run_file(file, local = FALSE, convert = convert)
5: reticulate::source_python(file = combine_pdfs_py_fpath)
6: demUtils::combine_pdfs(input_paths = input_paths, output_path = output_path)
An irrecoverable exception occurred. R is aborting now ...
SIGILL: illegal instruction
PC=0x473d9b m=0 sigcode=0

goroutine 1 [running, locked to thread]:
syscall.RawSyscall(0x3e, 0x45b, 0x4, 0x0, 0x0, 0xc0000d01e0, 0xc0000d01e0)
/usr/lib/golang/src/syscall/asm_linux_amd64.s:78 +0x2b fp=0xc000287ea8 sp=0xc000287ea0 pc=0x473d9b
syscall.Kill(0x45b, 0x4, 0x0, 0x0)
/usr/lib/golang/src/syscall/zsyscall_linux_amd64.go:597 +0x4b fp=0xc000287ef0 sp=0xc000287ea8 pc=0x470b9b
github.com/sylabs/singularity/internal/app/starter.Master.func4()
internal/app/starter/master_linux.go:158 +0x62 fp=0xc000287f38 sp=0xc000287ef0 pc=0x936562
github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute.func1()
internal/pkg/util/mainthread/mainthread.go:20 +0x2f fp=0xc000287f60 sp=0xc000287f38 pc=0x8cd18f
main.main()
cmd/starter/main_linux.go:102 +0x64 fp=0xc000287f98 sp=0xc000287f60 pc=0x936db4
runtime.main()
/usr/lib/golang/src/runtime/proc.go:200 +0x20c fp=0xc000287fe0 sp=0xc000287f98 pc=0x4321ac
runtime.goexit()
/usr/lib/golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000287fe8 sp=0xc000287fe0 pc=0x45d521

goroutine 19 [syscall]:
os/signal.signal_recv(0xb4a0c0)
/usr/lib/golang/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
/usr/lib/golang/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
/usr/lib/golang/src/os/signal/signal_unix.go:29 +0x41
```

**Comment by krpaulson** [comment]
This error above was from a qsub on my regular code (not the test code) on image `v2020.0.9`. But I just tried a test file on the IDE and it seems to have worked there.

File: R/combine_pdfs.R [hunk 1]
```diff
@@ -24,10 +24,16 @@ combine_pdfs <- function(input_paths, output_path) {
   assertthat::assert_that(all(fs::file_exists(input_paths)))
   assertthat::assert_that(fs::dir_exists(fs::path_dir(output_path)))
 
+  # replace `~` with users home directory for PyPDF2
```
Comment (krpaulson) [inline R/combine_pdfs.R]: Add a note in the function details field to not use symlinks or aliases in file paths.

**Review by krpaulson — DISMISSED** [review]

**Comment by chacalle** [comment]
> Ok so it wasn't `~` but I think we need to add instructions to not use any aliases (I was using a different IHME alias). Now I'm getting a different error.
> 
> ```
> 
> *** caught illegal operation ***
> address 0x2af0938a054c, cause 'illegal operand'
> 
> Traceback:
> 1: py_run_string_impl(paste0("import sys; sys.path.append('", system.file("python",     package = "reticulate"), "')"))
> 2: initialize_python(required_module, use_environment)
> 3: ensure_python_initialized()
> 4: py_run_file(file, local = FALSE, convert = convert)
> 5: reticulate::source_python(file = combine_pdfs_py_fpath)
> 6: demUtils::combine_pdfs(input_paths = input_paths, output_path = output_path)
> An irrecoverable exception occurred. R is aborting now ...
> SIGILL: illegal instruction
> PC=0x473d9b m=0 sigcode=0
> 
> goroutine 1 [running, locked to thread]:
> syscall.RawSyscall(0x3e, 0x45b, 0x4, 0x0, 0x0, 0xc0000d01e0, 0xc0000d01e0)
> /usr/lib/golang/src/syscall/asm_linux_amd64.s:78 +0x2b fp=0xc000287ea8 sp=0xc000287ea0 pc=0x473d9b
> syscall.Kill(0x45b, 0x4, 0x0, 0x0)
> /usr/lib/golang/src/syscall/zsyscall_linux_amd64.go:597 +0x4b fp=0xc000287ef0 sp=0xc000287ea8 pc=0x470b9b
> github.com/sylabs/singularity/internal/app/starter.Master.func4()
> internal/app/starter/master_linux.go:158 +0x62 fp=0xc000287f38 sp=0xc000287ef0 pc=0x936562
> github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute.func1()
> internal/pkg/util/mainthread/mainthread.go:20 +0x2f fp=0xc000287f60 sp=0xc000287f38 pc=0x8cd18f
> main.main()
> cmd/starter/main_linux.go:102 +0x64 fp=0xc000287f98 sp=0xc000287f60 pc=0x936db4
> runtime.main()
> /usr/lib/golang/src/runtime/proc.go:200 +0x20c fp=0xc000287fe0 sp=0xc000287f98 pc=0x4321ac
> runtime.goexit()
> /usr/lib/golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000287fe8 sp=0xc000287fe0 pc=0x45d521
> 
> goroutine 19 [syscall]:
> os/signal.signal_recv(0xb4a0c0)
> /usr/lib/golang/src/runtime/sigqueue.go:139 +0x9c
> os/signal.loop()
> /usr/lib/golang/src/os/signal/signal_unix.go:23 +0x22
> created by os/signal.init.0
> /usr/lib/golang/src/os/signal/signal_unix.go:29 +0x41
> ```

Are you still seeing this @krpaulson? I was waiting for more time to look into this more since its not immediately obvious what is going on.

**Comment by krpaulson** [comment]
I just tried my test code again twice, and it worked the first time, then gave me this same illegal operation error the second time.

File: R/combine_pdfs.R (hunk 1 above)
Comment (chacalle) [reply R/combine_pdfs.R]: Actually switched to `fs::path_real` which should resolve all these issues.

From the function description
```
path_real: returns the canonical path, eliminating any symbolic links and the special 
references ~, ~user, ., and .., , i.e. it calls path_expand() (literally) and path_norm() 
(effectively).
```

**Review by krpaulson — APPROVED** [review]

**Comment by krpaulson** [comment]
@chacalle combine pdfs function seems to be working without this change. should we close this PR?

**Comment by chacalle** [comment]
Probably working just cause we aren't including aliases in the input paths? I think it should be safe to merge in as an extra check
